### ISSUE TITLE
Tracking issue: Split label out of example object

### ISSUE THREAD

**Issue by jackgerrits** [VowpalWabbit/vowpal_wabbit#2324]
As a part of the atomization project we would like to split the label object out of example and additionally change the signature of learn/predict from:
```C++
void learn/predict(data&, LEARNER::single_learner&, example&);
```
to:
```C++
void learn/predict(data&, LEARNER::single_learner&, example&, label&);
void learn/predict(data&, LEARNER::single_learner&, example&, std::vector<label>&);
```

To do:
- [ ] Infrastructure to support learn/predict interop
- [ ] Convert finish example
- [ ] Convert output example
- [ ] Transform all reductions

**Comment by Shivanshmundra** [comment]
@jackgerrits are you taking up this issue or is it free to take? Since I have experience with labels in the example, I would love to take this issue.

**Comment by jackgerrits** [comment]
This is an in progress task that I am working on, this issue is to track progress.

**Comment by JohnLangford** [comment]
There is a good goal here, but we haven't had movement in some time, so I'll close this for now.  Further movement with patches is welcome.
