### ISSUE TITLE
Split apart reduction finish_example implementations

### ISSUE THREAD

**Issue by jackgerrits** [VowpalWabbit/vowpal_wabbit#4307]
`finish_example` should be replaced with the appropriate implementations of `output_prediction_example`, `print_update`, `update_stats` and `cleanup_example`

`finish_example` currently usually contains several things, which we want to split into separate functions:

- A call to `shared_data::update`-> Move to `update_stats` 
- A call to `shared_data::print`-> Move to `print_update` 
- Outputting predictions-> Move to `output_prediction_example` 
- Reusing memory or cleaning up the example -> `cleanup_example`

To migrate:
- [x] active #4353
- [x] audit_regressor #4358
- [x] automl #4419
- [x] boosting #4362 
- [x] bs #4366 
- [x] cats_pdf #4372
- [x] cats #4372
- [x] cbzo #4347 
- [x] confidence #4348 
- [x] count_label #4349 
- [x] cs_active #4394
- [x] csoaa_ldf #4452
- [x] csoaa #4446
- [x] ect #4424 
- [x] explore_eval #4448 
- [x] lda_core #4413
- [x] log_multi #4414
- [x] memory_tree #4412 
- [x] multilabel_oaa (#4340)
- [x] mwt (#4311)
- [x] nn (#4314)
- [x] oaa (#4316)
- [x] oja_newton #4350
- [x] plt (#4339)
- [x] recall_tree #4402
- [x] sender (#4321)
- [x] stagewise_poly (#4322)
- [x] topk (#4324)
- [x] cb_adf #4397
- [x] cb_algs #4409
- [x] cb_explore_adf_bag (#4330 ) start
- [x] cb_explore_adf_cover
- [x] cb_explore_adf_first
- [x] cb_explore_adf_greedy
- [x] cb_explore_adf_large_action_space
- [x] cb_explore_adf_regcb
- [x] cb_explore_adf_rnd
- [x] cb_explore_adf_softmax
- [x] cb_explore_adf_squarecb
- [x] cb_explore_adf_synthcover -- (#4330 ) end
- [x] cb_explore (#4360 )
- [x] cb_to_cb_adf (#4398 )
- [x] cbify #4440
- [x] warm_cb  #4447
- [x] search (#4400)
